version: '2.1'
services:
  docker-samba-dc:
    privileged: true
    build: '.'
    stdin_open: true
    network_mode: host
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - /data/docker/samba-dc/samba:/samba
    - /data/docker/samba-dc/resolv.conf:/etc/resolv.conf
    environment:
    - SAMBA_DC_REALM=samba.local
    - SAMBA_DC_ADMIN_PASSWD=Secret123
    - SAMBA_DC_ACTION=provision
    - SAMBA_DC_DNS_FORWARDER=1.1.1.1
    - SAMBA_DC_DOMAIN=SAMBA
    hostname: dc
    ports:
    - 37:37/udp
    - 53:53
    - 88:88
    - 123:123/udp
    - 135:135/tcp
    - 137:137/udp
    - 138:138/udp
    - 139:139
    - 389:389
    - 445:445
    - 464:464
    - 636:636/tcp
    - 49152-65535:49152-65535/tcp
    - 3268:3268/tcp
    - 3269:3269/tcp
